version: '3'

set: [errexit, nounset, pipefail]
shopt: [globstar]

includes:
  lint:
    taskfile: .taskfiles/lint.yml
    internal: true
  format:
    taskfile: .taskfiles/format.yml
    internal: true

tasks:
  init:
    desc: Initialize repositry
    cmds:
      - git config core.hooksPath .githooks
      - git config commit.template .gitmessage

  lint:
    desc: Run linters
    cmds:
      - task: lint:default
      - task: lint:brew

  lint:brew:
    desc: Lint Hombrew formulae
    internal: true
    sources:
      - ./Formula/*.rb
    cmds:
      - brew style .
      - brew rubocop --lint .

  format:
    desc: Run formatters
    cmds:
      - task: format:default
      - task: format:brew

  format:brew:
    desc: Format Hombrew formulae
    internal: true
    sources:
      - ./Formula/*.rb
    cmds:
      - brew style --fix .
      - brew rubocop --autocorrect .
