version: '3'

set: [errexit, nounset, pipefail]
shopt: [globstar]

includes:
  lint:
    taskfile: https://github.com/nikaro/meta/raw/main/taskfiles/lint.yml
    internal: true
  format:
    taskfile: https://github.com/nikaro/meta/raw/main/taskfiles/format.yml
    internal: true

tasks:
  init:
    desc: Initialize repositry
    cmds:
      - git config core.hooksPath .githooks
      - git config commit.template .gitmessage

  lint:
    desc: Run linters
    cmds:
      - task: lint:default
      - task: lint:brew

  lint:brew:
    desc: Lint Hombrew formulae
    sources:
      - ./Casks/*.rb
      - ./Formula/*.rb
    cmds:
      - brew style ./Casks/*.rb ./Formula/*.rb
      - brew rubocop --lint ./Casks/*.rb ./Formula/*.rb

  format:
    desc: Run formatters
    cmds:
      - task: format:default
      - task: format:brew

  format:brew:
    desc: Format Hombrew formulae
    sources:
      - ./Casks/*.rb
      - ./Formula/*.rb
    cmds:
      - brew style --fix ./Casks/*.rb ./Formula/*.rb
      - brew rubocop --autocorrect ./Casks/*.rb ./Formula/*.rb
