# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zabbixmon < Formula
  desc "CLI application to show currents alerts on Zabbix"
  homepage "https://github.con/nikaro/zabbixmon"
  version "0.3.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.3.0/zabbixmon_0.3.0_darwin_amd64.tar.gz"
      sha256 "4f869f71cf887d01bbc924559f03c59167cc3f702c307f5e36a9e652c937fa02"

      def install
        bin.install "zabbixmon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.3.0/zabbixmon_0.3.0_darwin_arm64.tar.gz"
      sha256 "a740e6c508a7e43c40a575a547d8e67e207076f5b7c5d27f015968346b34c00b"

      def install
        bin.install "zabbixmon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.3.0/zabbixmon_0.3.0_linux_amd64.tar.gz"
      sha256 "5fa251aac3c422b3f7a161032d2fb705fbf658df5b29278e12b26863736d589f"

      def install
        bin.install "zabbixmon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.3.0/zabbixmon_0.3.0_linux_arm64.tar.gz"
      sha256 "b513d468c49d7905974db4c28b3691acde31abef68fd86bdc00ba8660292b245"

      def install
        bin.install "zabbixmon"
      end
    end
  end

  test do
    system "#{bin}/zabbixmon", "--help"
  end
end
