# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zabbixmon < Formula
  desc "CLI application to show currents alerts on Zabbix."
  homepage "https://github.con/nikaro/zabbixmon"
  version "0.2.0"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.2.0/zabbixmon_0.2.0_darwin_arm64.tar.gz"
      sha256 "d574bde1a2c4e3ad954559414320a5769b20cf7cecbbaae000cac27f3162c608"

      def install
        bin.install "zabbixmon"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.2.0/zabbixmon_0.2.0_darwin_amd64.tar.gz"
      sha256 "26cadf5c7efa449945bb434ca6a3dd10bccadf08d2734f09b7e8e86d7ddffa73"

      def install
        bin.install "zabbixmon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.2.0/zabbixmon_0.2.0_linux_amd64.tar.gz"
      sha256 "2a5a0e9866e6d233a73d37b7aa69b576c5995cb4c1242744978265d1571a91b3"

      def install
        bin.install "zabbixmon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.2.0/zabbixmon_0.2.0_linux_arm64.tar.gz"
      sha256 "19dcfe8b5767ae3cfba245e92163ef162dc5d91b81364df563dfd24a849110dd"

      def install
        bin.install "zabbixmon"
      end
    end
  end

  test do
    system "#{bin}/zabbixmon --help"
  end
end
