# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devc < Formula
  desc "CLI tool to manage your devcontainers"
  homepage "https://github.con/nikaro/devc"
  version "1.0.0-beta.7"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.7/devc_1.0.0-beta.7_darwin_amd64.tar.gz"
      sha256 "9cea6ba2818c6b2362d8556e941c10a9272ff9d026169be208f14ef4a2f9edca"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.7/devc_1.0.0-beta.7_darwin_arm64.tar.gz"
      sha256 "09bf1454fe94052095849bd00f3dbfc66d18755128c09f1af693e2035bd435f3"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.7/devc_1.0.0-beta.7_linux_amd64.tar.gz"
      sha256 "9d24750a4c222ca5a7a0a58e524d892a9a7a7eb160156c0e29862562c03e2a2d"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.7/devc_1.0.0-beta.7_linux_arm64.tar.gz"
      sha256 "62aa081e92c9e92d349aec0f3e269cc82d0a4d4df8d936f73bd98973cdacf734"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
  end

  test do
    system "#{bin}/devc", "init"
  end
end
