# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devc < Formula
  desc "CLI tool to manage your devcontainers"
  homepage "https://github.con/nikaro/devc"
  version "1.0.0-beta.8"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.8/devc_1.0.0-beta.8_darwin_amd64.tar.gz"
      sha256 "d219dca03b92b01bb3fa9a77da95e6d09c5791383fd28d9b2636dd104ab098b5"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.8/devc_1.0.0-beta.8_darwin_arm64.tar.gz"
      sha256 "cbe648a432e474e86150fb4397b261af379e4feae2df3b7367e5ba9494664a79"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.8/devc_1.0.0-beta.8_linux_arm64.tar.gz"
      sha256 "a0ed699dc42dea6ec9ffee3fde5b4f4c31480dbabaf5e9bb338eb41bc2164edc"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.8/devc_1.0.0-beta.8_linux_amd64.tar.gz"
      sha256 "6d6b1b2b43847ff66adbbbcf67ec859618a36f5b26621f0a1aacaef0b15430c6"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
  end

  test do
    system "#{bin}/devc", "init"
  end
end
