# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devc < Formula
  desc "CLI tool to manage your devcontainers"
  homepage "https://github.con/nikaro/devc"
  version "1.0.0-beta.6"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.6/devc_1.0.0-beta.6_darwin_arm64.tar.gz"
      sha256 "fa575aa34ad083df23d16f503b621b63eacbbc7f9bc10e5da1dabbb2d6022ca0"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.6/devc_1.0.0-beta.6_darwin_amd64.tar.gz"
      sha256 "154e42d8bec03623581d6028fe061913f3c689563b6fd437fc70079ecb44b945"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.6/devc_1.0.0-beta.6_linux_arm64.tar.gz"
      sha256 "0cd744373641101f480f4c36eef227112eac6237b4a1c1e49d50a37aa3d58d11"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/devc/releases/download/v1.0.0-beta.6/devc_1.0.0-beta.6_linux_amd64.tar.gz"
      sha256 "82c65a1e2ecc79c18e78219f71ad106641e02e7bd459699e5b37188880fa590a"

      def install
        bin.install "devc"
        man1.install Dir["man/*"]
        bash_completion.install "completions/devc"
        fish_completion.install "completions/devc.fish"
        zsh_completion.install "completions/_devc"
      end
    end
  end

  test do
    system "#{bin}/devc", "init"
  end
end
