# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goresume < Formula
  desc "Build HTML/PDF resume from JSON/YAML/TOML"
  homepage "https://github.con/nikaro/goresume"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/goresume/releases/download/v0.1.4/goresume_0.1.4_darwin_amd64.tar.gz"
      sha256 "ff722c59aa9b31b8c9488c158b7bb0ac4b3a1f4b95533a8ab9b0878f653c5b11"

      def install
        bin.install "goresume"
        generate_completions_from_executable(bin/"goresume", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikaro/goresume/releases/download/v0.1.4/goresume_0.1.4_darwin_arm64.tar.gz"
      sha256 "9e4456c8981ee792e30245ccb7f6779e98065a13bd2ea236dfda1ea3e9256c6c"

      def install
        bin.install "goresume"
        generate_completions_from_executable(bin/"goresume", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikaro/goresume/releases/download/v0.1.4/goresume_0.1.4_linux_arm64.tar.gz"
      sha256 "6a96a62162e0e70e5aaac8ee78e3dd92aa675caf1ef2448acf2e4fa1ce257922"

      def install
        bin.install "goresume"
        generate_completions_from_executable(bin/"goresume", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/goresume/releases/download/v0.1.4/goresume_0.1.4_linux_amd64.tar.gz"
      sha256 "a3e4df021ce975b6eeb15794bd1459a443221947821a1cdfd5e42fc5c339c4f2"

      def install
        bin.install "goresume"
        generate_completions_from_executable(bin/"goresume", "completion")
      end
    end
  end
end
