# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goresume < Formula
  desc "Build HTML/PDF resume from JSON/YAML/TOML"
  homepage "https://github.con/nikaro/goresume"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nikaro/goresume/releases/download/0.2.6/goresume_0.2.6_darwin_arm64.tar.gz"
      sha256 "6e446db06c65fb61a24731614afd4b1ff131ae6bccffc1ef008eebfb4379933e"

      def install
        bin.install "goresume"
        generate_completions_from_executable(bin/"goresume", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/goresume/releases/download/0.2.6/goresume_0.2.6_darwin_amd64.tar.gz"
      sha256 "ad033878cb9b633d20bbfd8f32d74f7291fcb837767720af56bdec15f03d74bc"

      def install
        bin.install "goresume"
        generate_completions_from_executable(bin/"goresume", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikaro/goresume/releases/download/0.2.6/goresume_0.2.6_linux_arm64.tar.gz"
      sha256 "f119efb7cc8db809700407777442a58bca4e761b564e82be7386d002c982a2ce"

      def install
        bin.install "goresume"
        generate_completions_from_executable(bin/"goresume", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/goresume/releases/download/0.2.6/goresume_0.2.6_linux_amd64.tar.gz"
      sha256 "c2d7be68d3f0bb939317663d2771f23a60f465a6c1f2d74e8a614bcaf33823da"

      def install
        bin.install "goresume"
        generate_completions_from_executable(bin/"goresume", "completion")
      end
    end
  end
end
