# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zabbixmon < Formula
  desc "CLI application to show currents alerts on Zabbix"
  homepage "https://github.con/nikaro/zabbixmon"
  version "0.3.2"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.3.2/zabbixmon_0.3.2_darwin_amd64.tar.gz"
      sha256 "6d3c07a066870455f29fd8b784f46b1de8d13ddc228ebafa24937e3ae6e32562"

      def install
        bin.install "zabbixmon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.3.2/zabbixmon_0.3.2_darwin_arm64.tar.gz"
      sha256 "bc8b8402ee77e2b0af866efa55856f62b78b5e160afffb143d5c6213a1718d0e"

      def install
        bin.install "zabbixmon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.3.2/zabbixmon_0.3.2_linux_amd64.tar.gz"
      sha256 "d213f689f7ce1c4c4db0f946b41d94b6502bd68eef39c717a228aa662e16faad"

      def install
        bin.install "zabbixmon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikaro/zabbixmon/releases/download/v0.3.2/zabbixmon_0.3.2_linux_arm64.tar.gz"
      sha256 "e8d5de2df46d8bc8fb4b1480266fbd24b7153f330f7957f07bdb7f1f8136fde6"

      def install
        bin.install "zabbixmon"
      end
    end
  end

  test do
    system "#{bin}/zabbixmon", "--help"
  end
end
