name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Add brew to PATH
        shell: bash
        run: |-
          {
            echo "/home/linuxbrew/.linuxbrew/sbin";
            echo "/home/linuxbrew/.linuxbrew/bin";
          } >> "$GITHUB_PATH"

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@76fbdfa54e95397e420dd8ac2a98fff79fd317ee  # 1.7.0
