name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@266845213695c3047d210b2e8fbc42ecdaf45802  # master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@76fbdfa54e95397e420dd8ac2a98fff79fd317ee  # 1.7.0

  formula:
    name: Formula
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      changed: ${{ steps.changed-formulae.outputs.any_changed }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@266845213695c3047d210b2e8fbc42ecdaf45802  # master

      - name: Get changed formulae
        id: changed-formulae
        uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0  # v46.0.3
        with:
          files: |
            Formula/*.rb

      - name: Set up git
        if: steps.changed-formulae.outputs.any_changed == 'true'
        uses: Homebrew/actions/git-user-config@266845213695c3047d210b2e8fbc42ecdaf45802  # master

      - name: Cache Homebrew Bundler RubyGems
        if: steps.changed-formulae.outputs.any_changed == 'true'
        id: cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.changed-formulae.outputs.any_changed == 'true' && steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Run the pre-cleanup step
        if: steps.changed-formulae.outputs.any_changed == 'true'
        run: brew test-bot --only-cleanup-before

      - name: Run the local system check step
        if: steps.changed-formulae.outputs.any_changed == 'true'
        run: brew test-bot --only-setup

      - name: Run the tap syntax check step
        if: steps.changed-formulae.outputs.any_changed == 'true'
        run: brew test-bot --only-tap-syntax

      - name: Run the formulae steps
        if: steps.changed-formulae.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        run: brew test-bot --only-formulae --skip-relocation

      - name: Upload bottles as artifact
        if: always() && steps.changed-formulae.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: bottles_${{ matrix.os }}
          path: "*.bottle.*"

  check:
    name: Check
    permissions: {}
    runs-on: ubuntu-latest
    needs: [lint, formula]
    if: always()
    steps:
      - name: Ensure no jobs failed
        run: |-
          [ "${{ !contains(needs.*.result, 'failure') }}" = "true" ] || exit 1

  label:
    name: Label
    needs: [formula, check]
    if: github.event_name == 'pull_request' && needs.formula.outputs.changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Add merge label
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: gh pr edit "$PULL_REQUEST" --add-label "merge"
