name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@40f457b19d23d3f0a9a1ff4a978613773a2f228f # 1.6.0
