name: Publish

on:
  pull_request_target:
    types:
      - labeled

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-latest
    permissions:
      actions: write
      attestations: write
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      repository-projects: write
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_FROM_API: 1
      HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
      HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
      HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
      PULL_REQUEST: ${{ github.event.pull_request.number }}
    steps:
      - name: Checkout
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: gh repo clone ${{ github.repository }} ${{ github.workspace }} -- --depth=1 --branch "$BRANCH"

      - name: Configure git for a user
        run: |-
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add brew to PATH
        shell: bash
        run: |-
          {
            echo "/home/linuxbrew/.linuxbrew/sbin";
            echo "/home/linuxbrew/.linuxbrew/bin";
          } >> "$GITHUB_PATH"

      - name: Pull bottles
        id: pr-pull
        run: brew pr-pull --debug --retain-bottle-dir --no-upload --tap="$GITHUB_REPOSITORY" "$PULL_REQUEST"

      - name: Upload bottles to GitHub Packages
        working-directory: ${{ steps.pr-pull.outputs.bottle_path }}
        run: brew pr-upload --debug

      - name: Push commits
        run: |-
          credentials=$(echo -n "x-access-token:${{ github.token }}" | base64)
          git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic $credentials"
          git pull --rebase --autostash origin main
          git push

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin "$BRANCH"
