name: Publish

on:
  pull_request_target:
    types:
      - labeled

jobs:
  merge:
    name: Merge
    if: contains(github.event.pull_request.labels.*.name, 'merge')
    runs-on: ubuntu-latest
    permissions:
      actions: write
      attestations: write
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      repository-projects: write
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_FROM_API: 1
      HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
      HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
      HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
      PULL_REQUEST: ${{ github.event.pull_request.number }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@266845213695c3047d210b2e8fbc42ecdaf45802  # master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@266845213695c3047d210b2e8fbc42ecdaf45802  # master

      - name: Pull bottles
        id: pr-pull
        run: |-
          brew pr-pull \
            --debug \
            --retain-bottle-dir \
            --no-upload \
            --workflows="ci.yml" \
            --tap="$GITHUB_REPOSITORY" \
            "$PULL_REQUEST"

      - name: Upload bottles to GitHub Packages
        working-directory: ${{ steps.pr-pull.outputs.bottle_path }}
        env:
          REPO_PATH: ${{ steps.set-up-homebrew.outputs.repository-path }}
        run: brew pr-upload --debug

      - name: Push commits
        uses: Homebrew/actions/git-try-push@266845213695c3047d210b2e8fbc42ecdaf45802  # master
        with:
          token: ${{ github.token }}
          branch: main

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin "$BRANCH"
