name: Tests

on:
  pull_request:
    branches: [main]
    paths: ["Formula/**"]
  push:
    branches: [main]
    paths: ["Formula/**"]

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@266845213695c3047d210b2e8fbc42ecdaf45802  # master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@266845213695c3047d210b2e8fbc42ecdaf45802  # master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Run the pre-cleanup step
        run: brew test-bot --only-cleanup-before

      - name: Run the local system check step
        run: brew test-bot --only-setup

      - name: Run the tap syntax check step
        run: brew test-bot --only-tap-syntax

      - name: Run the formulae steps
        if: github.event_name == 'pull_request'
        run: brew test-bot --only-formulae

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: bottles_${{ matrix.os }}
          path: "*.bottle.*"
