name: Tests

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run tests
        run: brew test-bot

      - name: Upload bottles as artifact
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'
